# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
